chest14:
  name: "chest14"
  data_type: "imagetext"
  data_path: "datasets/chest14_train.csv"
  image_size: ${base.image_size}
  text_max_length: ${base.text_max_length}
  prompt_from_json: true
  data_frac: ${base.data_frac}
  num_negs: 3
