chexpert:
  name: "chexpert"
  data_type: "imagetext"
  data_path: "datasets/chexpert_train.csv"
  image_size: ${base.image_size}
  text_max_length: ${base.text_max_length}
  prompt_from_json: true
  data_frac: 1.0
